# Generated by Django 4.2.7 on 2023-11-12 22:41

import OCRApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=OCRApp.models.upload_to)),
            ],
        ),
    ]
