# Generated by Django 4.2.7 on 2023-12-02 11:32

import OCRApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCRApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to=OCRApp.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
