# Generated by Django 5.0 on 2023-12-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_appuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
