# Generated by Django 5.0 on 2023-12-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_customer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
