# Generated by Django 4.2.7 on 2023-11-12 22:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_address_customer_library_librarystaff_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MA', unique=True),
        ),
    ]
